# ===== Configurações Básicas do Nessie =====
nessie.server.default-branch=main
nessie.server.send-stacktrace-to-client=false
quarkus.http.port=19120
quarkus.management.port=9010
quarkus.log.level=INFO
quarkus.log.console.level=INFO
quarkus.log.console.json=false
#quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%X{traceId},%X{spanId},%X{sampled}] [%c{3.}] (%t) %s%e%n
quarkus.log.file.level=INFO
quarkus.log.file.json=false
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %h %N[%i] %-5p [%X{traceId},%X{spanId},%X{sampled}] [%c{3.}] (%t) %s%e%n



# ===== Configurações Globais do Iceberg (MinIO) =====
# Iceberg default config (can be overridden per warehouse)
nessie.catalog.iceberg-config-overrides.s3.ssl-enabled=false
nessie.catalog.iceberg-config-overrides.file-format=parquet

# Warehouses config
nessie.catalog.default-warehouse=s3a://iceberg/warehouse
nessie.catalog.warehouses.warehouse.iceberg-config-defaults.prop-name=prop-value
nessie.catalog.warehouses.warehouse.iceberg-config-overrides.prop-name=prop-value

# additional warehouses
nessie.catalog.warehouses.another-warehouse.location=<object-store-URI>

#storage object configurations -- MinIO
nessie.catalog.iceberg-config-defaults.s3.endpoint=http://minio:9000
nessie.catalog.iceberg-config-overrides.s3.path-style-access=true
nessie.catalog.iceberg-config-overrides.s3.access-key-id=minioadmin
nessie.catalog.iceberg-config-overrides.s3.secret-access-key=minioadmin

#health check configurations
nessie.catalog.object-stores.health-check.enabled=true
nessie.catalog.error-handling.throttled-retry-after=PT10S

#postgresql backend to store nessie metadada. != iceberg metadada
nessie.version.store.type=JDBC
nessie.version.store.jdbc.url=jdbc:postgresql://localhost:5435/nessiedb
nessie.version.store.jdbc.user=admin
nessie.version.store.jdbc.password=admin
nessie.version.store.jdbc.pool.max-size=10
nessie.version.store.jdbc.pool.min-size=2



# ===== Configurações Gerais do Spark =====
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
spark.sql.defaultCatalog=icebergdw  # Define o catálogo padrão

# ===== Configurações do Catálogo Iceberg/Nessie (icebergdw) =====
spark.sql.catalog.icebergdw=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.icebergdw.catalog-impl=org.apache.iceberg.nessie.NessieCatalog
spark.sql.catalog.icebergdw.uri=http://nessie:19120/api/v1  # URL do servidor Nessie
spark.sql.catalog.icebergdw.ref=main  # Branch padrão
spark.sql.catalog.icebergdw.warehouse=s3a://iceberg/warehouse  # Caminho no MinIO
spark.sql.catalog.icebergdw.authentication.type=NONE  # Se não usar autenticação

# ===== Configurações do MinIO (S3A) =====
spark.hadoop.fs.s3a.endpoint          http://minio:9000
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.access.key        minioadmin
spark.hadoop.fs.s3a.secret.key        minioadmin
spark.hadoop.fs.s3a.connection.ssl.enabled false