services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /dockervol/sparkjobs:/opt/airflow/sparkapps:rw
      - dockervol:/dockervol:rw
      - spark-logs:/opt/spark/spark-events:rwx # Logs do Spark

    ports:
      - 5433:5432
    networks:
      - hadoopcluster

  airflow:
    container_name: airflow
    image: airflow:airflow
    environment:
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/dbname
      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080

    volumes:
      - ./dags:/opt/airflow/dags:rw
      - /dockervol/sparkjobs:/opt/airflow/sparkapps:rw
      - dockervol:/dockervol:rw
      - spark-logs:/opt/spark/spark-events:rwx # Logs do Spark
    ports:
      - 8181:8080
    depends_on:
      - redis
      - postgres

    networks:
      - hadoopcluster
      
  redis:
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s

    volumes:
      - ./dags:/opt/airflow/dags:rw
      - /dockervol/sparkjobs:/opt/airflow/sparkapps:rw
      - dockervol:/dockervol:rw
      - spark-logs:/opt/spark/spark-events:rwx # Logs do Spark
    networks:
      - hadoopcluster

volumes:

  dockervol:
    external: true

  postgres_data:

  spark-logs:
    external: true

networks:
  hadoopcluster:
    external: true